name: pet_popularity

# pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
 
# pip install pandas==1.3.5 timm==0.4.12 ipykernel==6.6.1 opencv-python==4.4.0.46 pytorch-lightning==1.5.8

dependencies:
    - python==3.9.7
    - pip:
      - pandas==1.3.5
      - timm==0.4.12
      - ipykernel==6.6.1
      - opencv-python==4.4.0.46
      - pytorch-lightning==1.5.8
      - torch==1.9.0+cu111 
      - torchvision==0.10.0+cu111 
      - torchaudio==0.9.0
      